---
- name: Certs.yml | Install EasyRSA
  ansible.builtin.apt:
    name: "{{ easyrsa_name }}"
    state: present

- name: Certs.yml | Check folder /etc/openvpn/easy-rsa exists
  ansible.builtin.file:
    path: /etc/openvpn/easy-rsa
    state: directory
    mode: 0755

- name: Certs.yml | Check folder /etc/openvpn/keys exists
  ansible.builtin.file:
    path: "{{ openvpn_keys_dir }}"
    state: directory
    mode: 0600

- name: Certs.yml | EasyRSA init-pki
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa init-pki"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki

- name: Certs.yml | EasyRSA build-ca
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa build-ca nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/ca.crt
  environment:
    EASYRSA_BATCH: "yes"

- name: Certs.yml | EasyRSA gen-dh
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa gen-dh"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/dh.pem

- name: Certs.yml | EasyRSA build-server-full server nopass
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa build-server-full server nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/server.crt

- name: Certs.yml | EasyRSA build-client-full client nopass
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa build-client-full client nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/client.crt

- name: Certs.yml | EasyRSA gen-crl
  ansible.builtin.command:
    cmd: "{{ easyrsa_path }}/easyrsa gen-crl"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/crl.pem

- name: Certs.yml | Generate tls-auth key
  ansible.builtin.command:
    cmd: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
    creates: /etc/openvpn/easy-rsa/pki/ta.key

- name: Certs.yml | Copy files to /etc/openvpn/keys
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: "{{ openvpn_keys_dir }}/{{ item | basename }}"
    mode: 0640
    remote_src: true
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/client.crt
    - issued/server.crt
    - private/ca.key
    - private/client.key
    - private/server.key
