---
- name: Configure.yml | Copy config server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/server{{ openvpn_port }}.conf"
    owner: root
    group: root
    mode: 0640
  notify:
    - Restart openvpn
